#!/usr/bin/env bash
# Transfers file to a server

if [ -z "$3" ]
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
	scp -i "$4" -o StrictHostKeyChecking=no "$1" "$3@$2":~/
fi
