#!/usr/bin/env bash
# Installs and configures HAproxy on a new Ubuntu Server

sudo apt-get install -y --no-install-recommends software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.6
sudo apt-get -y update
apt-get install -y haproxy=2.6.\*

FRONT="frontend 27672-lb-01\n\tbind *:80\n\tmode http\n\n\tdefault_backend web_backend"
BACK="backend web-backend\n\tbalance roundrobin\n\tserver 27672-web-01 3.235.30.193:80 check\n\tserver 27672-web-02 35.170.82.237:80 check"

sudo echo -e $FRONT >> /etc/haproxy/haproxy.cfg
sudo echo -e $BACK >> /etc/haproxy/haproxy.cfg

sudo systemctl restart haproxy
