#!/usr/bin/env bash
#creates a file /var/run/myscript.pid containing its PID
#displays To infinity and beyond indefinitely
#displays I hate the kill command in SIGTERM
#Displays Y U no love me?! on SIGINT
#Deletes /var/run/myscript.pid on SIGQUIT or SIGTERM

SIGTERM_handler()
{
    echo "I hate the kill command"
    rm /var/run/myscript.pid
    exit 0
}

SIGINT_handler()
{
    echo "Y U no love me?!"
}

SIGQUIT_handler()
{
    rm /var/run/myscript.pid
    exit 0
}


trap "SIGTERM_handler" SIGTERM
trap "SIGINT_handler" SIGINT
trap "SIGQUIT_handler" SIGQUIT

pgrep -f 100-process_and_pid_file >> /var/run/myscript.pid
while $1
do
echo "To infinity and beyond";
sleep 2
done
